services:
  api:
    image: ghcr.io/ccrsxx/api:latest
    container_name: api
    restart: unless-stopped
    ports:
      - '4000:4000'
    env_file:
      - .env
    environment:
      - TZ=Asia/Jakarta
      - PORT=4000
      - APP_ENV=production
      - DATABASE_URL=postgres://postgres:${DATABASE_PASSWORD}@db:5432/postgres
    read_only: true
    cap_drop:
      - ALL
    security_opt:
      - 'no-new-privileges:true'
    user: '10001:10001'
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:18
    container_name: db
    restart: unless-stopped
    environment:
      - PGDATA=/data/postgres
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - '5444:5432'
    volumes:
      - db-data:/data/postgres
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5

  db-backup:
    image: prodrigestivill/postgres-backup-local:18
    container_name: db-backup
    restart: unless-stopped
    environment:
      - TZ=Asia/Jakarta
      - POSTGRES_DB=postgres
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_CLUSTER=true
      - SCHEDULE=@daily
      - BACKUP_KEEP_DAYS=7
    volumes:
      - /backup/database/api:/backups
    depends_on:
      db:
        condition: service_healthy

volumes:
  db-data:
