services:
  api:
    image: ghcr.io/ccrsxx/api:latest@sha256:9ff2a77ea2f29f5e819ab07acea914abbf78b2e1fd1b019e98d34acb140040e8
    container_name: api
    restart: unless-stopped
    ports:
      - '4000:4000'
    env_file:
      - .env
    environment:
      - TZ=Asia/Jakarta
      - PORT=4000
      - APP_ENV=production
      - DATABASE_URL=postgres://postgres:${DATABASE_PASSWORD}@db:5432/postgres
    read_only: true
    cap_drop:
      - ALL
    security_opt:
      - 'no-new-privileges:true'
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:18@sha256:22c89fe0d0f507606260237fd55e51f6137f58b2d5bcf6152242b96d9fe8f9a4
    container_name: db
    restart: unless-stopped
    environment:
      - TZ=Asia/Jakarta
      - PGDATA=/data/postgres
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - '5444:5432'
    volumes:
      - db-data:/data/postgres
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5

  db-backup:
    image: prodrigestivill/postgres-backup-local:18@sha256:f70742ebe42b2277689b028d1fd15aa80f77cffa01da163cc9f85a6ff1866e7f
    container_name: db-backup
    restart: unless-stopped
    environment:
      - TZ=Asia/Jakarta
      - POSTGRES_DB=postgres
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_CLUSTER=true
      - SCHEDULE=@daily
      - BACKUP_KEEP_DAYS=7
    volumes:
      - /backup/database/api:/backups
    depends_on:
      db:
        condition: service_healthy

volumes:
  db-data:
