// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: content_meta.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getContentLikeStatus = `-- name: GetContentLikeStatus :one
SELECT COALESCE(SUM(likes), 0)::bigint AS likes,
    COALESCE(
        SUM(likes) FILTER (
            WHERE ip_address_id = $1
        ),
        0
    )::bigint AS user_likes
FROM content_meta
WHERE content_id = $2
`

type GetContentLikeStatusParams struct {
	IpAddressID pgtype.UUID
	ContentID   pgtype.UUID
}

type GetContentLikeStatusRow struct {
	Likes     int64
	UserLikes int64
}

func (q *Queries) GetContentLikeStatus(ctx context.Context, arg GetContentLikeStatusParams) (GetContentLikeStatusRow, error) {
	row := q.db.QueryRow(ctx, getContentLikeStatus, arg.IpAddressID, arg.ContentID)
	var i GetContentLikeStatusRow
	err := row.Scan(&i.Likes, &i.UserLikes)
	return i, err
}

const getTotalContentMeta = `-- name: GetTotalContentMeta :one
SELECT COALESCE(SUM(views), 0)::bigint AS total_views,
    COALESCE(SUM(likes), 0)::bigint AS total_likes
FROM content_meta
WHERE content_id = $1
`

type GetTotalContentMetaRow struct {
	TotalViews int64
	TotalLikes int64
}

func (q *Queries) GetTotalContentMeta(ctx context.Context, contentID pgtype.UUID) (GetTotalContentMetaRow, error) {
	row := q.db.QueryRow(ctx, getTotalContentMeta, contentID)
	var i GetTotalContentMetaRow
	err := row.Scan(&i.TotalViews, &i.TotalLikes)
	return i, err
}

const incrementContentLike = `-- name: IncrementContentLike :one
INSERT INTO content_meta (content_id, ip_address_id, likes)
VALUES ($1, $2, 1) ON CONFLICT (content_id, ip_address_id) DO
UPDATE
SET likes = LEAST(content_meta.likes + 1, 5),
    updated_at = NOW()
RETURNING views,
    likes
`

type IncrementContentLikeParams struct {
	ContentID   pgtype.UUID
	IpAddressID pgtype.UUID
}

type IncrementContentLikeRow struct {
	Views int32
	Likes int32
}

func (q *Queries) IncrementContentLike(ctx context.Context, arg IncrementContentLikeParams) (IncrementContentLikeRow, error) {
	row := q.db.QueryRow(ctx, incrementContentLike, arg.ContentID, arg.IpAddressID)
	var i IncrementContentLikeRow
	err := row.Scan(&i.Views, &i.Likes)
	return i, err
}

const incrementContentView = `-- name: IncrementContentView :one
INSERT INTO content_meta (content_id, ip_address_id, views)
VALUES ($1, $2, 1) ON CONFLICT (content_id, ip_address_id) DO
UPDATE
SET views = content_meta.views + 1,
    updated_at = NOW()
RETURNING views,
    likes
`

type IncrementContentViewParams struct {
	ContentID   pgtype.UUID
	IpAddressID pgtype.UUID
}

type IncrementContentViewRow struct {
	Views int32
	Likes int32
}

func (q *Queries) IncrementContentView(ctx context.Context, arg IncrementContentViewParams) (IncrementContentViewRow, error) {
	row := q.db.QueryRow(ctx, incrementContentView, arg.ContentID, arg.IpAddressID)
	var i IncrementContentViewRow
	err := row.Scan(&i.Views, &i.Likes)
	return i, err
}
