// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: content.sql

package sqlc

import (
	"context"
)

const getContentBySlug = `-- name: GetContentBySlug :one
SELECT id, slug, kind, created_at, updated_at
FROM content
WHERE slug = $1
LIMIT 1
`

func (q *Queries) GetContentBySlug(ctx context.Context, slug string) (Content, error) {
	row := q.db.QueryRow(ctx, getContentBySlug, slug)
	var i Content
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Kind,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getContentStatsByType = `-- name: GetContentStatsByType :one
SELECT COUNT(DISTINCT c.id)::bigint AS total_posts,
    COALESCE(SUM(cm.views), 0)::bigint AS total_views,
    COALESCE(SUM(cm.likes), 0)::bigint AS total_likes
FROM content AS c
    LEFT JOIN content_meta AS cm ON c.id = cm.content_id
WHERE c.kind = $1
`

type GetContentStatsByTypeRow struct {
	TotalPosts int64 `json:"totalPosts"`
	TotalViews int64 `json:"totalViews"`
	TotalLikes int64 `json:"totalLikes"`
}

func (q *Queries) GetContentStatsByType(ctx context.Context, kind string) (GetContentStatsByTypeRow, error) {
	row := q.db.QueryRow(ctx, getContentStatsByType, kind)
	var i GetContentStatsByTypeRow
	err := row.Scan(&i.TotalPosts, &i.TotalViews, &i.TotalLikes)
	return i, err
}

const listContentByType = `-- name: ListContentByType :many
SELECT c.slug,
    COALESCE(SUM(cm.views), 0)::bigint AS views,
    COALESCE(SUM(cm.likes), 0)::bigint AS likes
FROM content c
    LEFT JOIN content_meta AS cm ON c.id = cm.content_id
WHERE c.kind = $1
GROUP BY c.id,
    c.slug
ORDER BY c.created_at
`

type ListContentByTypeRow struct {
	Slug  string `json:"slug"`
	Views int64  `json:"views"`
	Likes int64  `json:"likes"`
}

func (q *Queries) ListContentByType(ctx context.Context, kind string) ([]ListContentByTypeRow, error) {
	rows, err := q.db.Query(ctx, listContentByType, kind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListContentByTypeRow
	for rows.Next() {
		var i ListContentByTypeRow
		if err := rows.Scan(&i.Slug, &i.Views, &i.Likes); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertContent = `-- name: UpsertContent :one
INSERT INTO content (slug, kind)
VALUES ($1, $2) ON CONFLICT (slug) DO
UPDATE
SET slug = EXCLUDED.slug
RETURNING id, slug, kind, created_at, updated_at
`

type UpsertContentParams struct {
	Slug string `json:"slug"`
	Kind string `json:"kind"`
}

func (q *Queries) UpsertContent(ctx context.Context, arg UpsertContentParams) (Content, error) {
	row := q.db.QueryRow(ctx, upsertContent, arg.Slug, arg.Kind)
	var i Content
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Kind,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
