// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: content_like.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createContentLike = `-- name: CreateContentLike :exec
INSERT INTO content_like (content_id, ip_address_id)
VALUES ($1, $2)
`

type CreateContentLikeParams struct {
	ContentID   pgtype.UUID `json:"contentId"`
	IpAddressID pgtype.UUID `json:"ipAddressId"`
}

func (q *Queries) CreateContentLike(ctx context.Context, arg CreateContentLikeParams) error {
	_, err := q.db.Exec(ctx, createContentLike, arg.ContentID, arg.IpAddressID)
	return err
}

const getContentLikeStatus = `-- name: GetContentLikeStatus :one
SELECT COUNT(cl.id)::int AS likes,
       COUNT(cl.id) FILTER (WHERE cl.ip_address_id = $1)::int AS user_likes
FROM content_like cl
JOIN content c ON c.id = cl.content_id
WHERE c.slug = $2
`

type GetContentLikeStatusParams struct {
	IpAddressID pgtype.UUID `json:"ipAddressId"`
	Slug        string      `json:"slug"`
}

type GetContentLikeStatusRow struct {
	Likes     int32 `json:"likes"`
	UserLikes int32 `json:"userLikes"`
}

func (q *Queries) GetContentLikeStatus(ctx context.Context, arg GetContentLikeStatusParams) (GetContentLikeStatusRow, error) {
	row := q.db.QueryRow(ctx, getContentLikeStatus, arg.IpAddressID, arg.Slug)
	var i GetContentLikeStatusRow
	err := row.Scan(&i.Likes, &i.UserLikes)
	return i, err
}

const getUserLikeCount = `-- name: GetUserLikeCount :one
SELECT COUNT(*)::int AS user_likes
FROM content_like cl
JOIN content c ON c.id = cl.content_id
WHERE c.slug = $1
  AND cl.ip_address_id = $2
`

type GetUserLikeCountParams struct {
	Slug        string      `json:"slug"`
	IpAddressID pgtype.UUID `json:"ipAddressId"`
}

func (q *Queries) GetUserLikeCount(ctx context.Context, arg GetUserLikeCountParams) (int32, error) {
	row := q.db.QueryRow(ctx, getUserLikeCount, arg.Slug, arg.IpAddressID)
	var user_likes int32
	err := row.Scan(&user_likes)
	return user_likes, err
}
