// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: contact.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createContact = `-- name: CreateContact :one
INSERT INTO contact (name, email, message)
VALUES ($1, $2, $3)
RETURNING id, name, email, message, delivered_at, created_at, updated_at
`

type CreateContactParams struct {
	Name    string
	Email   string
	Message string
}

func (q *Queries) CreateContact(ctx context.Context, arg CreateContactParams) (Contact, error) {
	row := q.db.QueryRow(ctx, createContact, arg.Name, arg.Email, arg.Message)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Message,
		&i.DeliveredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateContactDeliveredAtByID = `-- name: UpdateContactDeliveredAtByID :one
UPDATE contact
SET delivered_at = NOW()
WHERE id = $1
RETURNING id, name, email, message, delivered_at, created_at, updated_at
`

func (q *Queries) UpdateContactDeliveredAtByID(ctx context.Context, id pgtype.UUID) (Contact, error) {
	row := q.db.QueryRow(ctx, updateContactDeliveredAtByID, id)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Message,
		&i.DeliveredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
