// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: content_view.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createContentView = `-- name: CreateContentView :exec
INSERT INTO content_view (content_id, ip_address_id)
VALUES ($1, $2)
`

type CreateContentViewParams struct {
	ContentID   pgtype.UUID `json:"contentId"`
	IpAddressID pgtype.UUID `json:"ipAddressId"`
}

func (q *Queries) CreateContentView(ctx context.Context, arg CreateContentViewParams) error {
	_, err := q.db.Exec(ctx, createContentView, arg.ContentID, arg.IpAddressID)
	return err
}

const getContentViewCount = `-- name: GetContentViewCount :one
SELECT COUNT(*)::int AS views
FROM content_view cv
JOIN content c ON c.id = cv.content_id
WHERE c.slug = $1
`

func (q *Queries) GetContentViewCount(ctx context.Context, slug string) (int32, error) {
	row := q.db.QueryRow(ctx, getContentViewCount, slug)
	var views int32
	err := row.Scan(&views)
	return views, err
}
