// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: guestboook.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createGuestbook = `-- name: CreateGuestbook :one
WITH new_guestbook AS (
    INSERT INTO guestbook (text, user_id)
    VALUES ($1, $2)
    RETURNING id, text, user_id, created_at, updated_at
)
SELECT g.id,
    g.text,
    u.name,
    u.role,
    u.image,
    a.username,
    g.created_at
FROM new_guestbook AS g
    JOIN users AS u ON g.user_id = u.id
    LEFT JOIN account AS a ON u.id = a.user_id
`

type CreateGuestbookParams struct {
	Text   string      `json:"text"`
	UserID pgtype.UUID `json:"userId"`
}

type CreateGuestbookRow struct {
	ID        pgtype.UUID        `json:"id"`
	Text      string             `json:"text"`
	Name      string             `json:"name"`
	Role      string             `json:"role"`
	Image     pgtype.Text        `json:"image"`
	Username  pgtype.Text        `json:"username"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
}

func (q *Queries) CreateGuestbook(ctx context.Context, arg CreateGuestbookParams) (CreateGuestbookRow, error) {
	row := q.db.QueryRow(ctx, createGuestbook, arg.Text, arg.UserID)
	var i CreateGuestbookRow
	err := row.Scan(
		&i.ID,
		&i.Text,
		&i.Name,
		&i.Role,
		&i.Image,
		&i.Username,
		&i.CreatedAt,
	)
	return i, err
}

const deleteGuestbook = `-- name: DeleteGuestbook :exec
DELETE FROM guestbook
WHERE id = $1
`

func (q *Queries) DeleteGuestbook(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteGuestbook, id)
	return err
}

const getGuestbookByID = `-- name: GetGuestbookByID :one
SELECT id, text, user_id, created_at, updated_at
FROM guestbook
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetGuestbookByID(ctx context.Context, id pgtype.UUID) (Guestbook, error) {
	row := q.db.QueryRow(ctx, getGuestbookByID, id)
	var i Guestbook
	err := row.Scan(
		&i.ID,
		&i.Text,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listGuestbook = `-- name: ListGuestbook :many
SELECT g.id,
    g.text,
    u.name,
    u.role,
    u.image,
    a.username,
    g.created_at
FROM guestbook AS g
    JOIN users AS u ON g.user_id = u.id
    LEFT JOIN account AS a ON u.id = a.user_id
ORDER BY g.created_at DESC
`

type ListGuestbookRow struct {
	ID        pgtype.UUID        `json:"id"`
	Text      string             `json:"text"`
	Name      string             `json:"name"`
	Role      string             `json:"role"`
	Image     pgtype.Text        `json:"image"`
	Username  pgtype.Text        `json:"username"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
}

func (q *Queries) ListGuestbook(ctx context.Context) ([]ListGuestbookRow, error) {
	rows, err := q.db.Query(ctx, listGuestbook)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGuestbookRow
	for rows.Next() {
		var i ListGuestbookRow
		if err := rows.Scan(
			&i.ID,
			&i.Text,
			&i.Name,
			&i.Role,
			&i.Image,
			&i.Username,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
