// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ip_address.sql

package sqlc

import (
	"context"
)

const upsertIPAddress = `-- name: UpsertIPAddress :one
INSERT INTO ip_address (ip_address)
VALUES ($1) ON CONFLICT (ip_address) DO
UPDATE
SET ip_address = EXCLUDED.ip_address
RETURNING id, ip_address, created_at, updated_at
`

func (q *Queries) UpsertIPAddress(ctx context.Context, ipAddress string) (IpAddress, error) {
	row := q.db.QueryRow(ctx, upsertIPAddress, ipAddress)
	var i IpAddress
	err := row.Scan(
		&i.ID,
		&i.IpAddress,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
