// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID                pgtype.UUID        `json:"id"`
	UserID            pgtype.UUID        `json:"userId"`
	Provider          string             `json:"provider"`
	ProviderAccountID string             `json:"providerAccountId"`
	Username          pgtype.Text        `json:"username"`
	CreatedAt         pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt         pgtype.Timestamptz `json:"updatedAt"`
}

type Content struct {
	ID        pgtype.UUID        `json:"id"`
	Slug      string             `json:"slug"`
	Type      string             `json:"type"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt pgtype.Timestamptz `json:"updatedAt"`
}

type ContentLike struct {
	ID          pgtype.UUID        `json:"id"`
	ContentID   pgtype.UUID        `json:"contentId"`
	IpAddressID pgtype.UUID        `json:"ipAddressId"`
	CreatedAt   pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt   pgtype.Timestamptz `json:"updatedAt"`
}

type ContentView struct {
	ID          pgtype.UUID        `json:"id"`
	ContentID   pgtype.UUID        `json:"contentId"`
	IpAddressID pgtype.UUID        `json:"ipAddressId"`
	CreatedAt   pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt   pgtype.Timestamptz `json:"updatedAt"`
}

type Guestbook struct {
	ID        pgtype.UUID        `json:"id"`
	Text      string             `json:"text"`
	UserID    pgtype.UUID        `json:"userId"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt pgtype.Timestamptz `json:"updatedAt"`
}

type IpAddress struct {
	ID        pgtype.UUID        `json:"id"`
	IpAddress string             `json:"ipAddress"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt pgtype.Timestamptz `json:"updatedAt"`
}

type User struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Role      string             `json:"role"`
	Image     pgtype.Text        `json:"image"`
	Email     pgtype.Text        `json:"email"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt pgtype.Timestamptz `json:"updatedAt"`
}
