// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID                pgtype.UUID
	UserID            pgtype.UUID
	Provider          string
	ProviderAccountID string
	Username          pgtype.Text
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type Content struct {
	ID        pgtype.UUID
	Slug      string
	Type      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type ContentLike struct {
	ID          pgtype.UUID
	ContentID   pgtype.UUID
	IpAddressID pgtype.UUID
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type ContentView struct {
	ID          pgtype.UUID
	ContentID   pgtype.UUID
	IpAddressID pgtype.UUID
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type Guestbook struct {
	ID        pgtype.UUID
	Text      string
	UserID    pgtype.UUID
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type IpAddress struct {
	ID        pgtype.UUID
	IpAddress string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type User struct {
	ID        pgtype.UUID
	Name      string
	Role      string
	Image     pgtype.Text
	Email     pgtype.Text
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
