// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateGuestbook(ctx context.Context, arg CreateGuestbookParams) (CreateGuestbookRow, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteGuestbook(ctx context.Context, id pgtype.UUID) error
	GetAccountByProvider(ctx context.Context, arg GetAccountByProviderParams) (Account, error)
	GetContentBySlug(ctx context.Context, slug string) (Content, error)
	GetContentLikeStatus(ctx context.Context, arg GetContentLikeStatusParams) (GetContentLikeStatusRow, error)
	GetContentStatsByType(ctx context.Context, type_ string) (GetContentStatsByTypeRow, error)
	GetGuestbookByID(ctx context.Context, id pgtype.UUID) (Guestbook, error)
	GetTotalContentMeta(ctx context.Context, contentID pgtype.UUID) (GetTotalContentMetaRow, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserWithAccountByID(ctx context.Context, id pgtype.UUID) (GetUserWithAccountByIDRow, error)
	IncrementContentLike(ctx context.Context, arg IncrementContentLikeParams) (IncrementContentLikeRow, error)
	IncrementContentView(ctx context.Context, arg IncrementContentViewParams) (IncrementContentViewRow, error)
	ListContentByType(ctx context.Context, type_ string) ([]ListContentByTypeRow, error)
	ListGuestbook(ctx context.Context) ([]ListGuestbookRow, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpsertContent(ctx context.Context, arg UpsertContentParams) (Content, error)
	UpsertIPAddress(ctx context.Context, ipAddress string) (IpAddress, error)
}

var _ Querier = (*Queries)(nil)
