// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO account (user_id, provider, provider_account_id, username)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, provider, provider_account_id, username, created_at, updated_at
`

type CreateAccountParams struct {
	UserID            pgtype.UUID `json:"userId"`
	Provider          string      `json:"provider"`
	ProviderAccountID string      `json:"providerAccountId"`
	Username          pgtype.Text `json:"username"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.UserID,
		arg.Provider,
		arg.ProviderAccountID,
		arg.Username,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderAccountID,
		&i.Username,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (name, image, email)
VALUES ($1, $2, $3)
RETURNING id, name, role, image, email, created_at, updated_at
`

type CreateUserParams struct {
	Name  string      `json:"name"`
	Image pgtype.Text `json:"image"`
	Email pgtype.Text `json:"email"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Name, arg.Image, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Role,
		&i.Image,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountByProvider = `-- name: GetAccountByProvider :one
SELECT id, user_id, provider, provider_account_id, username, created_at, updated_at
FROM account
WHERE provider = $1
    AND provider_account_id = $2
LIMIT 1
`

type GetAccountByProviderParams struct {
	Provider          string `json:"provider"`
	ProviderAccountID string `json:"providerAccountId"`
}

func (q *Queries) GetAccountByProvider(ctx context.Context, arg GetAccountByProviderParams) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByProvider, arg.Provider, arg.ProviderAccountID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderAccountID,
		&i.Username,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, role, image, email, created_at, updated_at
FROM users
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Role,
		&i.Image,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserWithAccountByID = `-- name: GetUserWithAccountByID :one
SELECT u.id, name, role, image, email, u.created_at, u.updated_at, a.id, user_id, provider, provider_account_id, username, a.created_at, a.updated_at
FROM users AS u
    JOIN account AS a ON u.id = a.user_id
WHERE u.id = $1
LIMIT 1
`

type GetUserWithAccountByIDRow struct {
	ID                pgtype.UUID        `json:"id"`
	Name              string             `json:"name"`
	Role              string             `json:"role"`
	Image             pgtype.Text        `json:"image"`
	Email             pgtype.Text        `json:"email"`
	CreatedAt         pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt         pgtype.Timestamptz `json:"updatedAt"`
	ID_2              pgtype.UUID        `json:"id2"`
	UserID            pgtype.UUID        `json:"userId"`
	Provider          string             `json:"provider"`
	ProviderAccountID string             `json:"providerAccountId"`
	Username          pgtype.Text        `json:"username"`
	CreatedAt_2       pgtype.Timestamptz `json:"createdAt2"`
	UpdatedAt_2       pgtype.Timestamptz `json:"updatedAt2"`
}

func (q *Queries) GetUserWithAccountByID(ctx context.Context, id pgtype.UUID) (GetUserWithAccountByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserWithAccountByID, id)
	var i GetUserWithAccountByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Role,
		&i.Image,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ID_2,
		&i.UserID,
		&i.Provider,
		&i.ProviderAccountID,
		&i.Username,
		&i.CreatedAt_2,
		&i.UpdatedAt_2,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET name = $1,
    image = $2,
    updated_at = NOW()
WHERE id = $3
RETURNING id, name, role, image, email, created_at, updated_at
`

type UpdateUserParams struct {
	Name  string      `json:"name"`
	Image pgtype.Text `json:"image"`
	ID    pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser, arg.Name, arg.Image, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Role,
		&i.Image,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
